/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import java.sql.*;
import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;
/**
 *
 * @author N3mesis
 */
public class InformacionUsuarios extends javax.swing.JFrame {
    //user_update = servirá para recuperar la seleccion del usuario q haya sido seleccionada
    String user ="", user_update ="";
    int ID;
    /**
     * Creates new form InformacionUsuarios
     */
    public InformacionUsuarios() {
        initComponents();
        //Centrar la interfaz al ejecutar
        //Almacenamos el usuario de la clase login en la variable user
        user = login.user;
        //Desde la interfaz gestionar usuarios, guardamos el dato que haya sido seleccionado
        //en la variable user_update
        user_update = GestionarUsuarios.user_update;
        //Definimos tamaño
        setSize(630, 450);
        setResizable(false);
        setTitle("Informacion de usuario " + user_update + " - Sesion de " + user);
        setLocationRelativeTo(null);
        //Nos permite evitar que el programa finalice cuando esta interfaz finalice
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        ImageIcon fondo = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        //creamos nuevo objeto para definir las dimesiones de la imagen
        //y se ajusten a nuestro JLabel
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(jbl_wallpaper.getWidth(), 
                jbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        //colocar la imagen que estamos escalando dentro del jlabel
        jbl_wallpaper.setIcon(icono);
        this.repaint();
        
        jbl_titulo.setText("Informacion del usuario " + user_update);
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbl_titulo = new javax.swing.JLabel();
        jbl_nombre = new javax.swing.JLabel();
        jbl_nombre1 = new javax.swing.JLabel();
        jbl_nombre2 = new javax.swing.JLabel();
        jbl_nombre3 = new javax.swing.JLabel();
        jbl_nombre4 = new javax.swing.JLabel();
        jbl_nombre5 = new javax.swing.JLabel();
        jbl_nombre6 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_mail = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_registrado = new javax.swing.JTextField();
        cmb_niveles = new javax.swing.JComboBox<>();
        cmb_status = new javax.swing.JComboBox<>();
        jButton_actualizar = new javax.swing.JButton();
        jButton_restaurarpass = new javax.swing.JButton();
        jLabel_footer = new javax.swing.JLabel();
        jbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbl_titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jbl_titulo.setText("Informacion de Usuario");
        getContentPane().add(jbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jbl_nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre.setText("Nombre:");
        getContentPane().add(jbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jbl_nombre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre1.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre1.setText("emaik:");
        getContentPane().add(jbl_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jbl_nombre2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre2.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre2.setText("Telefono:");
        getContentPane().add(jbl_nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jbl_nombre3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre3.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre3.setText("Permisos de:");
        getContentPane().add(jbl_nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jbl_nombre4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre4.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre4.setText("Username:");
        getContentPane().add(jbl_nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jbl_nombre5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre5.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre5.setText("Status:");
        getContentPane().add(jbl_nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        jbl_nombre6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre6.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre6.setText("Registrado por:");
        getContentPane().add(jbl_nombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        txt_nombre.setBackground(new java.awt.Color(253, 253, 255));
        txt_nombre.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        txt_mail.setBackground(new java.awt.Color(253, 253, 255));
        txt_mail.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_mail.setForeground(new java.awt.Color(255, 255, 255));
        txt_mail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_mail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

        txt_telefono.setBackground(new java.awt.Color(253, 253, 255));
        txt_telefono.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_telefono.setForeground(new java.awt.Color(255, 255, 255));
        txt_telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_telefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, -1));

        txt_username.setBackground(new java.awt.Color(253, 253, 255));
        txt_username.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 210, -1));

        txt_registrado.setBackground(new java.awt.Color(253, 253, 255));
        txt_registrado.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_registrado.setForeground(new java.awt.Color(255, 255, 255));
        txt_registrado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_registrado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_registrado.setEnabled(false);
        getContentPane().add(txt_registrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 210, -1));

        cmb_niveles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Capturista", "Tecnico" }));
        getContentPane().add(cmb_niveles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        cmb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        getContentPane().add(cmb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        jButton_actualizar.setBackground(new java.awt.Color(153, 153, 255));
        jButton_actualizar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_actualizar.setText("Actualizar Usuario");
        jButton_actualizar.setBorder(null);
        getContentPane().add(jButton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 210, 35));

        jButton_restaurarpass.setBackground(new java.awt.Color(153, 153, 255));
        jButton_restaurarpass.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_restaurarpass.setForeground(new java.awt.Color(255, 255, 255));
        jButton_restaurarpass.setText("Restaurar Password");
        jButton_restaurarpass.setBorder(null);
        getContentPane().add(jButton_restaurarpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 210, 35));

        jLabel_footer.setText("Practicando programación Java");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));
        getContentPane().add(jbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_niveles;
    private javax.swing.JComboBox<String> cmb_status;
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JButton jButton_restaurarpass;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JLabel jbl_nombre;
    private javax.swing.JLabel jbl_nombre1;
    private javax.swing.JLabel jbl_nombre2;
    private javax.swing.JLabel jbl_nombre3;
    private javax.swing.JLabel jbl_nombre4;
    private javax.swing.JLabel jbl_nombre5;
    private javax.swing.JLabel jbl_nombre6;
    private javax.swing.JLabel jbl_titulo;
    private javax.swing.JLabel jbl_wallpaper;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_registrado;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
