/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Giampier
 */
public class InformacionEquipo extends javax.swing.JFrame {
    
    int Idcliente_update = 0, IDequipo = 0;
    String user = "", nom_cliente = "";
    /**
     * Creates new form InformacionEquipo
     */
    public InformacionEquipo() {
        initComponents();
        user = login.user;
        IDequipo = Informacion_Clientes.IDequipo;
        Idcliente_update = GestionarClientes.IDcliente_update;
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
            "select nombre_cliente from clientes where idclientes ='" + Idcliente_update + "'");
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                nom_cliente = rs.getString("nombre_cliente");
            }
        } catch (Exception e) {
            System.err.println("Error al consultar el nombre del cliente" + e);
        }
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
            "select * from equipos where idequipos = '" + IDequipo + "'");
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                cmb_tipoequipo.setSelectedItem(rs.getString("tipo_equipo"));
                cmb_marcas.setSelectedItem(rs.getString("marca"));
                cmb_status.setSelectedItem(rs.getString("status"));
                txt_modelo.setText(rs.getString("modelo"));
                txt_numSerie.setText(rs.getString("num_serie"));
                txt_ultmodi.setText(rs.getString("ultima_modificacion"));
                
//                procedimiento para obtener las fechas
                String dia="", mes="", annio="";
                dia = rs.getString("dia_ingreso");
                mes = rs.getString("mes_ingreso");
                annio = rs.getString("annio_ingreso");
                txt_fecha.setText(dia + " del " + mes + " del " + annio);
                
                jTextPane_observaciones.setText(rs.getString("observaciones"));
                jTextPane_comentariosTecnicos.setText(rs.getString("comentarios_tecnicos"));
                jlabel_revtecnicade.setText("Comentarios y actualuizacion del tecnico: " + rs.getString("revision_tecnica"));
                
                
            }
            
        } catch (Exception e) {
            System.err.println("Erro al consultar la informacion del equipo");
        }
        setTitle("Equipo del cliente " + nom_cliente);
        setSize(670, 530);
        setResizable(false);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        ImageIcon fondo = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        //creamos nuevo objeto para definir las dimesiones de la imagen
        //y se ajusten a nuestro JLabel
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(jlabel_wallpapper.getWidth(),
                jlabel_wallpapper.getHeight(), Image.SCALE_DEFAULT));
        //colocar la imagen que estamos escalando dentro del jlabel
        jlabel_wallpapper.setIcon(icono);
        this.repaint();
        
        txt_nombreCliente.setText(nom_cliente);
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbl_titulo = new javax.swing.JLabel();
        jbl_nombre = new javax.swing.JLabel();
        jbl_nombre1 = new javax.swing.JLabel();
        jbl_nombre2 = new javax.swing.JLabel();
        jbl_nombre3 = new javax.swing.JLabel();
        jbl_nombre4 = new javax.swing.JLabel();
        jbl_nombre5 = new javax.swing.JLabel();
        jbl_nombre6 = new javax.swing.JLabel();
        jbl_nombre7 = new javax.swing.JLabel();
        jbl_nombre8 = new javax.swing.JLabel();
        jlabel_revtecnicade = new javax.swing.JLabel();
        txt_nombreCliente = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        txt_numSerie = new javax.swing.JTextField();
        txt_ultmodi = new javax.swing.JTextField();
        txt_fecha = new javax.swing.JTextField();
        cmb_tipoequipo = new javax.swing.JComboBox<>();
        cmb_marcas = new javax.swing.JComboBox<>();
        cmb_status = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane_observaciones = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane_comentariosTecnicos = new javax.swing.JTextPane();
        jButton_actualizar = new javax.swing.JButton();
        jLabel_footer = new javax.swing.JLabel();
        jlabel_wallpapper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbl_titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jbl_titulo.setText("Informacion de Equipo");
        getContentPane().add(jbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jbl_nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre.setText("Nombre del cliente:");
        getContentPane().add(jbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jbl_nombre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre1.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre1.setText("Tipo de equipo:");
        getContentPane().add(jbl_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jbl_nombre2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre2.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre2.setText("Marca:");
        getContentPane().add(jbl_nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jbl_nombre3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre3.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre3.setText("Modelo:");
        getContentPane().add(jbl_nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jbl_nombre4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre4.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre4.setText("Numero de Serie:");
        getContentPane().add(jbl_nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jbl_nombre5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre5.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre5.setText("Fecha de ingreso:");
        getContentPane().add(jbl_nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        jbl_nombre6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre6.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre6.setText("Ultima modificacion por:");
        getContentPane().add(jbl_nombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jbl_nombre7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre7.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre7.setText("Estatus:");
        getContentPane().add(jbl_nombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        jbl_nombre8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre8.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre8.setText("Danio Reportado y observaciones:");
        getContentPane().add(jbl_nombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jlabel_revtecnicade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlabel_revtecnicade.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_revtecnicade.setText("Comentarios y actualizacion del Tecnico:");
        getContentPane().add(jlabel_revtecnicade, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        txt_nombreCliente.setBackground(new java.awt.Color(153, 153, 255));
        txt_nombreCliente.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_nombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombreCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombreCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_nombreCliente.setEnabled(false);
        getContentPane().add(txt_nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, -1));

        txt_modelo.setBackground(new java.awt.Color(153, 153, 255));
        txt_modelo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_modelo.setForeground(new java.awt.Color(255, 255, 255));
        txt_modelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_modelo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 210, -1));

        txt_numSerie.setBackground(new java.awt.Color(153, 153, 255));
        txt_numSerie.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_numSerie.setForeground(new java.awt.Color(255, 255, 255));
        txt_numSerie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_numSerie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_numSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 210, -1));

        txt_ultmodi.setBackground(new java.awt.Color(153, 153, 255));
        txt_ultmodi.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_ultmodi.setForeground(new java.awt.Color(255, 255, 255));
        txt_ultmodi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ultmodi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_ultmodi.setEnabled(false);
        getContentPane().add(txt_ultmodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 210, -1));

        txt_fecha.setBackground(new java.awt.Color(153, 153, 255));
        txt_fecha.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_fecha.setForeground(new java.awt.Color(255, 255, 255));
        txt_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fecha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_fecha.setEnabled(false);
        getContentPane().add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 180, -1));

        cmb_tipoequipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Desktop", "Impresora", "Multifuncional" }));
        getContentPane().add(cmb_tipoequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        cmb_marcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acer", "Alenware", "Apple", "Asus", "Brother", "Dell", "HP", "Lenovo", "Samsung", "Toshiba", "Xerox" }));
        getContentPane().add(cmb_marcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        cmb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo Ingreso", "No reparado", "En revision", "Reparado", "Entregado" }));
        getContentPane().add(cmb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        jScrollPane1.setViewportView(jTextPane_observaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 330, 120));

        jTextPane_comentariosTecnicos.setEnabled(false);
        jScrollPane2.setViewportView(jTextPane_comentariosTecnicos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 330, 120));

        jButton_actualizar.setBackground(new java.awt.Color(153, 153, 255));
        jButton_actualizar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_actualizar.setText("Actualizar Equipo");
        jButton_actualizar.setBorder(null);
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 210, 35));

        jLabel_footer.setText("Practicando programación Java");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));
        getContentPane().add(jlabel_wallpapper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed
        // TODO add your handling code here:
        int validacion = 0;
        String tipo_equipo, marca, modelo, num_serie, status, observaciones;
        
        tipo_equipo = cmb_tipoequipo.getSelectedItem().toString();
        marca = cmb_marcas.getSelectedItem().toString();
        status = cmb_status.getSelectedItem().toString();
        modelo = txt_modelo.getText().trim();
        num_serie = txt_numSerie.getText().trim();
        observaciones = jTextPane_observaciones.getText();
        
        if(modelo.equals("")){
            txt_modelo.setBackground(Color.red);
            validacion++;
        }
        if(num_serie.equals("")){
            txt_numSerie.setBackground(Color.red);
            validacion++;
        }
        if(observaciones.equals("")){
            jTextPane_observaciones.setText("Sin observaciones.");
        }
        if (validacion == 0) {
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                "update equipos set tipo_equipo=?, marca=?, modelo=?, num_serie=?, observaciones=?, status=?, ultima_modificacion=? "
                        + "where idequipos = '" +IDequipo +"'");
                
                pst.setString(1, tipo_equipo);
                pst.setString(2, marca);
                pst.setString(3, modelo);
                pst.setString(4, num_serie);
                pst.setString(5, observaciones);
                pst.setString(6, status);
                pst.setString(7, user);
                
                pst.executeUpdate();
                cn.close();
                
                Limpiar();
                txt_nombreCliente.setBackground(Color.green);
                txt_fecha.setBackground(Color.green);
                txt_modelo.setBackground(Color.green);
                txt_numSerie.setBackground(Color.green);
                txt_ultmodi.setText(user);
                
                JOptionPane.showMessageDialog(null, "Actualizacion correcta");
                this.dispose();
                
            } catch (SQLException e) {
                System.err.println("Erro en actualizar equipo " + e);
                JOptionPane.showMessageDialog(null, "Error a actualizar equipo, contacte al administrador");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos");
        }
    }//GEN-LAST:event_jButton_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_marcas;
    private javax.swing.JComboBox<String> cmb_status;
    private javax.swing.JComboBox<String> cmb_tipoequipo;
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane_comentariosTecnicos;
    private javax.swing.JTextPane jTextPane_observaciones;
    private javax.swing.JLabel jbl_nombre;
    private javax.swing.JLabel jbl_nombre1;
    private javax.swing.JLabel jbl_nombre2;
    private javax.swing.JLabel jbl_nombre3;
    private javax.swing.JLabel jbl_nombre4;
    private javax.swing.JLabel jbl_nombre5;
    private javax.swing.JLabel jbl_nombre6;
    private javax.swing.JLabel jbl_nombre7;
    private javax.swing.JLabel jbl_nombre8;
    private javax.swing.JLabel jbl_titulo;
    private javax.swing.JLabel jlabel_revtecnicade;
    private javax.swing.JLabel jlabel_wallpapper;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_nombreCliente;
    private javax.swing.JTextField txt_numSerie;
    private javax.swing.JTextField txt_ultmodi;
    // End of variables declaration//GEN-END:variables
    public void Limpiar(){
        txt_nombreCliente.setText("");
        txt_fecha.setText("");
        txt_modelo.setText("");
        txt_numSerie.setText("");
        jTextPane_observaciones.setText("");
    }

}
