/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import clases.Conexion;
import javax.swing.JOptionPane;
/**
 *
 * @author N3mesis
 */
public class login extends javax.swing.JFrame {
    public static String user = "";
    String pass = "";
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        //Definimos el tamaño
        setSize(400, 550);
        //Evitamos que el usuario modifique el tamaño
        setResizable(false);
        //Cambiamos el titulo
        setTitle("Acceso al sistema");
        //Centrar la interfaz en la pantalla
        setLocationRelativeTo(null);
        //creamos objeto fondo
        ImageIcon fondo = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        //creamos nuevo objeto para definir las dimesiones de la imagen
        //y se ajusten a nuestro JLabel
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(JLabel_fondo.getWidth(), 
                JLabel_fondo.getHeight(), Image.SCALE_DEFAULT));
        //colocar la imagen que estamos escalando dentro del jlabel
        JLabel_fondo.setIcon(icono);
        this.repaint();
        //DEFINIENDO EL LOGO
        //creamos objeto
        ImageIcon wallpaper_logo = new ImageIcon("src/images/DS.png");
        //Creamos objeto para definirlas dimensiones de la imagen
        Icon icono_logo = new ImageIcon(wallpaper_logo.getImage().getScaledInstance(JLabel_logo.getWidth(),
            JLabel_logo.getHeight(), Image.SCALE_DEFAULT));
        JLabel_logo.setIcon(icono_logo);
        this.repaint();
    }
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel_logo = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        jButton_acceder = new javax.swing.JButton();
        jLabel_footer = new javax.swing.JLabel();
        JLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(JLabel_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 40, 270, 270));

        txt_user.setBackground(new java.awt.Color(153, 153, 255));
        txt_user.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_user.setForeground(new java.awt.Color(255, 255, 255));
        txt_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_user.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 330, 210, -1));

        txt_pass.setBackground(new java.awt.Color(153, 153, 255));
        txt_pass.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(255, 255, 255));
        txt_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 370, 210, -1));

        jButton_acceder.setBackground(new java.awt.Color(153, 153, 255));
        jButton_acceder.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_acceder.setForeground(new java.awt.Color(255, 255, 255));
        jButton_acceder.setText("Acceder");
        jButton_acceder.setBorder(null);
        jButton_acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_accederActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 420, 210, 37));

        jLabel_footer.setText("Practicando Java Giampier Arellano B.");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));
        getContentPane().add(JLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_accederActionPerformed
        // TODO add your handling code here:
        user = txt_user.getText().trim();
        pass = txt_pass.getText().trim();
        if(!user.equals("")||!pass.equals("")){
            try{
                //Establecemos la conexion, llamamos al metodo conectar
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                    "select tipo_nivel, status from usuarios where username = '" +user
                     + "' and password = '" + pass + "'");
                //ejecutar la instruccion anterior
                ResultSet rs = pst.executeQuery();
                if(rs.next()){
                    String tipo_nivel = rs.getString("tipo_nivel");
                    String status = rs.getString("status");
                    
                    if(tipo_nivel.equalsIgnoreCase("Administrador") && status.equalsIgnoreCase("Activo")){
                        dispose();
                        new Administrador().setVisible(true);
                    }else if(tipo_nivel.equalsIgnoreCase("Capturista") && status.equalsIgnoreCase("Activo")){
                        dispose();
                        new Capturista().setVisible(true);
                    }else if(tipo_nivel.equalsIgnoreCase("Tecnico") && status.equalsIgnoreCase("Activo")){
                        dispose();
                        new Tecnico().setVisible(true);
                    }
                    
                }else {
                    JOptionPane.showMessageDialog(null, "Datos de acceso incorrectos.");
                    txt_user.setText("");
                    txt_pass.setText("");
                }
                
            } catch (SQLException e){
                //mensaje para el programador
                System.out.println("Error en el botón acceder. "+e);
                //mensaje para el usuario
                JOptionPane.showMessageDialog(null, "Error al iniciar sesion, contacte al administrador");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos");
        }
    }//GEN-LAST:event_jButton_accederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel_fondo;
    private javax.swing.JLabel JLabel_logo;
    private javax.swing.JButton jButton_acceder;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
