/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
/**
 *
 * @author Giampier
 */
public class RegistrarEquipo extends javax.swing.JFrame {
    
    int idcliente_update = 0;
    String user = "", nom_cliente = "";
    /**
     * Creates new form RegistrarEquipo
     */
    public RegistrarEquipo() {
        initComponents();
        user = login.user;
        idcliente_update = GestionarClientes.IDcliente_update;
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select nombre_cliente from clientes where idclientes = '" + idcliente_update + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                nom_cliente = rs.getString("nombre_cliente");
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al consultar el nombre del cliente");
//            JOptionPane.showMessageDialog(null, "Error al cargar!, contacte al administrador");
        }
        setTitle("Registrar nuevo equipo para " + nom_cliente);
        setSize(630, 445);
        setResizable(false);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        //Nos permite evitar que el programa finalice cuando esta interfaz finalice
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        ImageIcon fondo = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        //creamos nuevo objeto para definir las dimesiones de la imagen
        //y se ajusten a nuestro JLabel
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(Jlabel_wallpaper.getWidth(),
                Jlabel_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        //colocar la imagen que estamos escalando dentro del jlabel
        Jlabel_wallpaper.setIcon(icono);
        this.repaint();
        
        txt_nombrecliente.setText(nom_cliente);
    }

    @Override
        public Image getIconImage
        
            (){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
            return retValue;
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane_observaciones = new javax.swing.JTextPane();
        jbl_titulo = new javax.swing.JLabel();
        jbl_nombre = new javax.swing.JLabel();
        jbl_nombre1 = new javax.swing.JLabel();
        jbl_nombre2 = new javax.swing.JLabel();
        jbl_nombre3 = new javax.swing.JLabel();
        jbl_nombre4 = new javax.swing.JLabel();
        jbl_nombre5 = new javax.swing.JLabel();
        txt_nombrecliente = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        txt_numSerie = new javax.swing.JTextField();
        cmb_tipoequipo = new javax.swing.JComboBox<>();
        cmb_marca = new javax.swing.JComboBox<>();
        jButton_registrar = new javax.swing.JButton();
        jLabel_footer = new javax.swing.JLabel();
        Jlabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(jTextPane_observaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 330, 230));

        jbl_titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jbl_titulo.setText("Registro de Equipo");
        getContentPane().add(jbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jbl_nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre.setText("Nombre del cliente:");
        getContentPane().add(jbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jbl_nombre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre1.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre1.setText("Tipo de Equipo:");
        getContentPane().add(jbl_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jbl_nombre2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre2.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre2.setText("Marca:");
        getContentPane().add(jbl_nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jbl_nombre3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre3.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre3.setText("Modelo:");
        getContentPane().add(jbl_nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jbl_nombre4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre4.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre4.setText("Numero de Serie:");
        getContentPane().add(jbl_nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jbl_nombre5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbl_nombre5.setForeground(new java.awt.Color(255, 255, 255));
        jbl_nombre5.setText("Dano reportado y observaciones:");
        getContentPane().add(jbl_nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        txt_nombrecliente.setBackground(new java.awt.Color(153, 153, 255));
        txt_nombrecliente.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_nombrecliente.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombrecliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombrecliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_nombrecliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, -1));

        txt_modelo.setBackground(new java.awt.Color(153, 153, 255));
        txt_modelo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_modelo.setForeground(new java.awt.Color(255, 255, 255));
        txt_modelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_modelo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 210, -1));

        txt_numSerie.setBackground(new java.awt.Color(153, 153, 255));
        txt_numSerie.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_numSerie.setForeground(new java.awt.Color(255, 255, 255));
        txt_numSerie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_numSerie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_numSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 210, -1));

        cmb_tipoequipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Desktop", "Multifuncional" }));
        getContentPane().add(cmb_tipoequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        cmb_marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acer", "Alenware", "Apple", "Asus", "Brother", "Dell", "HP", "Lenovo", "Samsung", "Toshiba", "Xerox" }));
        getContentPane().add(cmb_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jButton_registrar.setBackground(new java.awt.Color(153, 153, 255));
        jButton_registrar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_registrar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_registrar.setText("Registrar Equipo");
        jButton_registrar.setBorder(null);
        jButton_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 210, 35));

        jLabel_footer.setText("Practicando programación Java");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));
        getContentPane().add(Jlabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 445));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registrarActionPerformed
        // TODO add your handling code here:
        int validacion = 0;
//        Declaramos variables
        String tipo_equipo, marca, modelo, num_serie, dia_ingreso, mes_ingreso,
            anio_ingreso, status, observaciones;
        
        tipo_equipo = cmb_tipoequipo.getSelectedItem().toString();
        marca = cmb_marca.getSelectedItem().toString();
        modelo = txt_modelo.getText().trim();
        num_serie = txt_numSerie.getText().trim();
        observaciones = jTextPane_observaciones.getText();
        status = "nuevo ingreso";
        
//        Creamos objeto para utilizar la libreria calendar
        Calendar calendar = Calendar.getInstance();
        
//        Saber que dia ingreso el equipo (dia que se registra el equipo
        dia_ingreso = Integer.toString(calendar.get(Calendar.DATE));
        mes_ingreso = Integer.toString(calendar.get(Calendar.MONTH));
        anio_ingreso = Integer.toString(calendar.get(Calendar.YEAR));
        
//        Validar campos para que no queden vacios
        
         if(modelo.equals("")){
             txt_modelo.setBackground(Color.red);
             validacion++;
         }
         if(num_serie.equals("")){
             txt_numSerie.setBackground(Color.red);
             validacion++;
         }
         if(observaciones.equals("")){
             jTextPane_observaciones.setText("Sin observaciones");
         }
         
         if (validacion == 0){
             try {
                 Connection cn = Conexion.conectar();
                 PreparedStatement pst = cn.prepareStatement(
                    "insert into equipos values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                 
                 pst.setInt(1,0);
                 pst.setInt(2, idcliente_update);
                 pst.setString(3, tipo_equipo);
                 pst.setString(4, marca);
                 pst.setString(5, modelo);
                 pst.setString(6, num_serie);
                 pst.setString(7, dia_ingreso);
                 pst.setString(8, mes_ingreso);
                 pst.setString(9, anio_ingreso);
                 pst.setString(10, observaciones);
                 pst.setString(11, status);
                 pst.setString(12, user);
                 pst.setString(13, "");
                 pst.setString(14, "");
                 
                 pst.executeUpdate();
                 cn.close();
                 
                 txt_nombrecliente.setBackground(Color.GREEN);
                 txt_modelo.setBackground(Color.GREEN);
                 txt_numSerie.setBackground(Color.GREEN);
                 
                 JOptionPane.showMessageDialog(null, "Registro exitoso.");
                 this.dispose();
                 
             } catch (SQLException e) {
                 System.out.println("Erroe en registrar equipo. "+ e);
                 JOptionPane.showMessageDialog(null, "Error al registrar equipo, contacte al administrador");
             }
         }else {
             JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos");
         }
    }//GEN-LAST:event_jButton_registrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel_wallpaper;
    private javax.swing.JComboBox<String> cmb_marca;
    private javax.swing.JComboBox<String> cmb_tipoequipo;
    private javax.swing.JButton jButton_registrar;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane_observaciones;
    private javax.swing.JLabel jbl_nombre;
    private javax.swing.JLabel jbl_nombre1;
    private javax.swing.JLabel jbl_nombre2;
    private javax.swing.JLabel jbl_nombre3;
    private javax.swing.JLabel jbl_nombre4;
    private javax.swing.JLabel jbl_nombre5;
    private javax.swing.JLabel jbl_titulo;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_nombrecliente;
    private javax.swing.JTextField txt_numSerie;
    // End of variables declaration//GEN-END:variables
}
