/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
/**
 *
 * @author N3mesis
 */
public class RestaurarPass extends javax.swing.JFrame {
    String user = "", user_update="";
    /**
     * Creates new form RestaurarPass
     */
    public RestaurarPass() {
        initComponents();
        user = login.user;
        user_update = GestionarUsuarios.user_update;
        setSize(360,260);
        setResizable(false);
        setTitle("Cambio de password para"+ user_update);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon fondo = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        //creamos nuevo objeto para definir las dimesiones de la imagen
        //y se ajusten a nuestro JLabel
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(jbl_wallpaper.getWidth(), 
                jbl_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        //colocar la imagen que estamos escalando dentro del jlabel
        jbl_wallpaper.setIcon(icono);
        this.repaint();
    }
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        txt_passconfir = new javax.swing.JPasswordField();
        jButton_restaurarpass = new javax.swing.JButton();
        jbl_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cambio de Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nuevo Password:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Confirmar Password:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txt_password.setBackground(new java.awt.Color(153, 153, 255));
        txt_password.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        txt_passconfir.setBackground(new java.awt.Color(153, 153, 255));
        txt_passconfir.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_passconfir.setForeground(new java.awt.Color(255, 255, 255));
        txt_passconfir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_passconfir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_passconfir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, -1));

        jButton_restaurarpass.setBackground(new java.awt.Color(153, 153, 255));
        jButton_restaurarpass.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_restaurarpass.setForeground(new java.awt.Color(255, 255, 255));
        jButton_restaurarpass.setText("Restaurar Password");
        jButton_restaurarpass.setBorder(null);
        jButton_restaurarpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_restaurarpassActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_restaurarpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 210, 35));
        getContentPane().add(jbl_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_restaurarpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_restaurarpassActionPerformed
        // TODO add your handling code here:
        String password, confirmacion_pass;
        password = txt_password.getText().trim();
        confirmacion_pass = txt_passconfir.getText().trim();
        if(!password.equals("") && !confirmacion_pass.equals("")){
            if (password.equals(confirmacion_pass)){
                try{
                    Connection cn = Conexion.conectar();
                    PreparedStatement pst = cn.prepareStatement(
                        "update usuarios set password=? where username = '"+ user_update + "'");
                    pst.setString(1, password);
                    pst.executeUpdate();
                    cn.close();
                    txt_password.setBackground(Color.green);
                    txt_passconfir.setBackground(Color.green);
                    JOptionPane.showMessageDialog(null, "Restauracion exitosa");
                    this.dispose();
                    
                }catch (SQLException e){
                    System.out.println("Error al restaurar password "+e);
                }
            }else{
                txt_passconfir.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "Las constraseñas no coinciden");
            }
            
        }else {
            txt_password.setBackground(Color.RED);
            txt_passconfir.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "No se admiten contraseñas vacias");
        }
    }//GEN-LAST:event_jButton_restaurarpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurarPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurarPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurarPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurarPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurarPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_restaurarpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jbl_wallpaper;
    private javax.swing.JPasswordField txt_passconfir;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
